// Biblioteca completa de documentos LOPIVI para delegados de protección

export interface DocumentoLOPIVI {
  id: string
  titulo: string
  descripcion: string
  categoria: string
  tamaño: string
  contenido: string[]
  esencial: boolean
}

// Contenidos completos de los 8 PDFs organizados
export const DOCUMENTOS_LOPIVI: DocumentoLOPIVI[] = [
  {
    id: 'manual-lopivi',
    titulo: 'Manual LOPIVI Completo',
    descripcion: 'Guía fundamental con marco legal, funciones del delegado y casos prácticos',
    categoria: 'Formación Básica',
    tamaño: '2.3 MB - 58 páginas',
    esencial: true,
    contenido: [
      '1. INTRODUCCIÓN A LA LOPIVI',
      '- Marco legal y antecedentes normativos',
      '- Objetivos y principios fundamentales',
      '- Ámbito de aplicación en entidades deportivas',
      '- Derechos del menor en el deporte',
      '',
      '2. EL DELEGADO DE PROTECCIÓN',
      '- Perfil profesional y requisitos',
      '- Funciones y responsabilidades principales',
      '- Diferencias entre delegado principal y suplente',
      '- Coordinación con otros profesionales',
      '- Herramientas de trabajo esenciales',
      '',
      '3. DETECCIÓN DE SITUACIONES DE RIESGO',
      '- Indicadores físicos de maltrato',
      '- Señales comportamentales y emocionales',
      '- Factores de riesgo en el entorno deportivo',
      '- Técnicas de observación sistemática',
      '- Diferenciación entre disciplina deportiva y maltrato',
      '- Documentación adecuada de observaciones',
      '',
      '4. PROTOCOLOS DE COMUNICACIÓN',
      '- Comunicación efectiva con menores',
      '- Información apropiada a las familias',
      '- Coordinación con equipos técnicos',
      '- Comunicación con autoridades competentes',
      '- Confidencialidad y protección de datos',
      '- Registro y documentación de comunicaciones',
      '',
      '5. ACTUACIÓN EN EMERGENCIAS',
      '- Evaluación rápida de situaciones críticas',
      '- Protocolos de actuación inmediata',
      '- Contacto con servicios de emergencia',
      '- Protección del menor en riesgo',
      '- Seguimiento post-emergencia',
      '',
      '6. FORMACIÓN DEL PERSONAL',
      '- Diseño de programas formativos internos',
      '- Sensibilización del equipo técnico',
      '- Evaluación de competencias',
      '- Creación de cultura de protección',
      '- Actualización continua de conocimientos',
      '',
      '7. CASOS PRÁCTICOS',
      '- Caso 1: Detección de maltrato físico',
      '- Caso 2: Acoso entre menores',
      '- Caso 3: Comportamiento inadecuado del personal',
      '- Caso 4: Negligencia en supervisión',
      '- Caso 5: Comunicación con familias difíciles',
      '',
      '8. RECURSOS Y CONTACTOS',
      '- Directorio de servicios especializados',
      '- Formularios y plantillas útiles',
      '- Legislación aplicable actualizada',
      '- Bibliografía y recursos adicionales'
    ]
  },

  {
    id: 'plan-proteccion',
    titulo: 'Plan de Protección Template',
    descripcion: 'Plantilla personalizable para crear el plan de protección de tu entidad',
    categoria: 'Documentación Obligatoria',
    tamaño: '1.8 MB - 42 páginas',
    esencial: true,
    contenido: [
      'PLAN DE PROTECCIÓN INTEGRAL - [NOMBRE ENTIDAD]',
      '',
      '1. IDENTIFICACIÓN DE LA ENTIDAD',
      '- Datos de la entidad deportiva',
      '- Tipo de actividades realizadas',
      '- Número de menores atendidos',
      '- Personal involucrado',
      '- Instalaciones y espacios utilizados',
      '',
      '2. POLÍTICA DE PROTECCIÓN',
      '- Declaración de compromiso',
      '- Principios fundamentales',
      '- Objetivos específicos',
      '- Alcance y aplicación',
      '',
      '3. CÓDIGO DE CONDUCTA',
      '- Comportamientos esperados',
      '- Límites y prohibiciones claras',
      '- Relaciones apropiadas con menores',
      '- Uso de redes sociales y comunicación',
      '- Manejo de situaciones privadas',
      '',
      '4. PROCEDIMIENTOS DE SELECCIÓN DEL PERSONAL',
      '- Verificación de antecedentes',
      '- Entrevistas específicas',
      '- Período de prueba supervisado',
      '- Formación obligatoria inicial',
      '',
      '5. PROTOCOLOS DE ACTUACIÓN',
      '- Protocolo de detección de riesgo',
      '- Protocolo de actuación inmediata',
      '- Protocolo de comunicación interna',
      '- Protocolo de comunicación externa',
      '- Protocolo de seguimiento',
      '',
      '6. SISTEMA DE DENUNCIAS',
      '- Canales de denuncia disponibles',
      '- Procedimiento de recepción',
      '- Investigación interna',
      '- Medidas cautelares',
      '- Resolución y seguimiento',
      '',
      '7. FORMACIÓN CONTINUA',
      '- Programa de formación inicial',
      '- Actualización anual obligatoria',
      '- Formación específica por roles',
      '- Evaluación de competencias',
      '',
      '8. SUPERVISIÓN Y CONTROL',
      '- Sistema de supervisión regular',
      '- Evaluaciones periódicas',
      '- Auditorías internas',
      '- Revisión y actualización del plan',
      '',
      '9. COMUNICACIÓN CON FAMILIAS',
      '- Información sobre políticas',
      '- Canales de comunicación abiertos',
      '- Participación en la protección',
      '- Feedback y sugerencias',
      '',
      '10. ANEXOS',
      '- Formularios específicos',
      '- Contactos de emergencia',
      '- Legislación aplicable',
      '- Cronograma de implementación'
    ]
  },

  {
    id: 'protocolos-actuacion',
    titulo: 'Protocolos de Actuación',
    descripcion: 'Procedimientos paso a paso para emergencias y situaciones de riesgo',
    categoria: 'Procedimientos',
    tamaño: '1.5 MB - 35 páginas',
    esencial: true,
    contenido: [
      'PROTOCOLOS DE ACTUACIÓN LOPIVI',
      '',
      'PROTOCOLO 1: EMERGENCIA INMEDIATA',
      '1. EVALUACIÓN INICIAL (primeros 5 minutos)',
      '- Asegurar la seguridad inmediata del menor',
      '- Evaluar necesidad de atención médica',
      '- Aislar al menor de la situación de riesgo',
      '- No contaminar evidencias físicas',
      '',
      '2. COMUNICACIÓN INMEDIATA (siguientes 15 minutos)',
      '- Llamar al 112 si hay riesgo vital',
      '- Contactar servicios sociales de urgencia',
      '- Informar a la dirección de la entidad',
      '- NO contactar a la familia hasta evaluar situación',
      '',
      '3. DOCUMENTACIÓN INMEDIATA',
      '- Registrar fecha, hora y circunstancias',
      '- Documentar estado físico y emocional del menor',
      '- Identificar testigos presentes',
      '- Fotografiar lesiones si las hay (con permiso)',
      '',
      'PROTOCOLO 2: DETECCIÓN DE RIESGO',
      '1. OBSERVACIÓN SISTEMÁTICA',
      '- Cambios comportamentales significativos',
      '- Indicadores físicos de maltrato',
      '- Relatos del menor o terceros',
      '- Patrones repetitivos preocupantes',
      '',
      '2. VALORACIÓN PROFESIONAL',
      '- Contrastar observaciones con otros profesionales',
      '- Evaluar gravedad y urgencia',
      '- Documentar todas las observaciones',
      '- Decidir nivel de intervención necesario',
      '',
      '3. PLAN DE ACCIÓN',
      '- Medidas de protección inmediatas',
      '- Comunicaciones necesarias',
      '- Seguimiento programado',
      '- Evaluación continua',
      '',
      'PROTOCOLO 3: COMUNICACIÓN CON MENORES',
      '1. PREPARACIÓN DEL ENTORNO',
      '- Espacio privado y seguro',
      '- Sin interrupciones',
      '- Presencia de persona de confianza si es necesario',
      '- Ambiente relajado y acogedor',
      '',
      '2. TÉCNICAS DE COMUNICACIÓN',
      '- Escucha activa y empática',
      '- Preguntas abiertas, no inductivas',
      '- Respetar silencios y ritmos',
      '- Validar emociones del menor',
      '- No prometer confidencialidad absoluta',
      '',
      '3. REGISTRO DE LA CONVERSACIÓN',
      '- Documentar literalmente declaraciones',
      '- Registrar emociones y reacciones',
      '- Anotar fecha, hora, duración',
      '- Identificar personas presentes',
      '',
      'PROTOCOLO 4: COMUNICACIÓN CON FAMILIAS',
      '1. EVALUACIÓN PREVIA',
      '- Evaluar si la familia puede ser parte del problema',
      '- Valorar reacciones esperadas',
      '- Preparar información a transmitir',
      '- Decidir momento y lugar apropiados',
      '',
      '2. PROCESO DE COMUNICACIÓN',
      '- Informar de forma clara y objetiva',
      '- Explicar medidas adoptadas',
      '- Escuchar reacciones y preocupaciones',
      '- Acordar próximos pasos',
      '',
      '3. SEGUIMIENTO',
      '- Documentar la comunicación',
      '- Programar siguientes contactos',
      '- Coordinar con otros profesionales',
      '- Evaluar evolución de la situación'
    ]
  },

  {
    id: 'gestion-personal',
    titulo: 'Gestión del Personal',
    descripcion: 'Herramientas para formar, evaluar y supervisar al equipo de trabajo',
    categoria: 'Recursos Humanos',
    tamaño: '1.2 MB - 28 páginas',
    esencial: false,
    contenido: [
      'GESTIÓN DEL PERSONAL EN PROTECCIÓN DE MENORES',
      '',
      '1. CÓDIGO DE CONDUCTA PARA EL PERSONAL',
      '',
      'COMPORTAMIENTOS ESPERADOS:',
      '- Trato respetuoso y profesional en todo momento',
      '- Comunicación apropiada y constructiva',
      '- Supervisión adecuada según la edad de los menores',
      '- Respeto por la privacidad y dignidad',
      '- Confidencialidad de información sensible',
      '',
      'LÍMITES CLAROS:',
      '- No contacto físico inapropiado',
      '- No estar a solas con un menor sin supervisión',
      '- No intercambio de información personal',
      '- No comunicación privada fuera del horario',
      '- No regalos o favores especiales',
      '',
      'PROHIBICIONES ABSOLUTAS:',
      '- Cualquier forma de castigo físico',
      '- Humillaciones o ridiculizaciones',
      '- Discriminación por cualquier motivo',
      '- Uso de lenguaje inapropiado',
      '- Consumo de alcohol o drogas en las instalaciones',
      '',
      '2. PROGRAMA DE FORMACIÓN INICIAL',
      '',
      'MÓDULO 1: FUNDAMENTOS LOPIVI (4 horas)',
      '- Marco legal y obligaciones',
      '- Derechos de los menores',
      '- Responsabilidades del personal',
      '- Políticas de la entidad',
      '',
      'MÓDULO 2: DETECCIÓN Y PREVENCIÓN (3 horas)',
      '- Identificación de señales de alarma',
      '- Factores de riesgo',
      '- Técnicas de observación',
      '- Primeros auxilios psicológicos',
      '',
      'MÓDULO 3: PROTOCOLOS DE ACTUACIÓN (3 horas)',
      '- Procedimientos paso a paso',
      '- Comunicación efectiva',
      '- Documentación adecuada',
      '- Trabajo en equipo',
      '',
      '3. EVALUACIÓN DE COMPETENCIAS',
      '',
      'EVALUACIÓN INICIAL:',
      '- Test de conocimientos básicos',
      '- Casos prácticos simulados',
      '- Observación en situaciones reales',
      '- Feedback de compañeros y supervisores',
      '',
      'EVALUACIÓN CONTINUA:',
      '- Revisiones trimestrales',
      '- Autoevaluación reflexiva',
      '- Evaluación 360 grados',
      '- Plan de mejora individual',
      '',
      '4. SUPERVISIÓN Y APOYO',
      '',
      'SUPERVISIÓN REGULAR:',
      '- Reuniones semanales de equipo',
      '- Observación directa periódica',
      '- Revisión de documentación',
      '- Feedback constructivo constante',
      '',
      'APOYO PROFESIONAL:',
      '- Consulta con expertos',
      '- Grupos de apoyo entre pares',
      '- Formación continua',
      '- Recursos adicionales disponibles',
      '',
      '5. GESTIÓN DE SITUACIONES DIFÍCILES',
      '',
      'PROCEDIMIENTO DISCIPLINARIO:',
      '- Investigación imparcial',
      '- Medidas cautelares si es necesario',
      '- Derecho a defensa',
      '- Resolución documentada',
      '- Seguimiento post-resolución',
      '',
      'APOYO AL PERSONAL AFECTADO:',
      '- Soporte emocional',
      '- Asesoramiento legal si procede',
      '- Protección ante represalias',
      '- Acompañamiento en el proceso'
    ]
  },

  {
    id: 'documentos-operativos',
    titulo: 'Documentos Operativos',
    descripcion: 'Formularios, registros y plantillas para el trabajo diario',
    categoria: 'Herramientas de Trabajo',
    tamaño: '0.9 MB - 22 páginas',
    esencial: false,
    contenido: [
      'DOCUMENTOS OPERATIVOS LOPIVI',
      '',
      '1. FORMULARIO DE REPORTE DE INCIDENTES',
      '',
      'DATOS BÁSICOS:',
      '- Fecha y hora del incidente: ___________',
      '- Lugar específico: ___________',
      '- Personas involucradas: ___________',
      '- Testigos presentes: ___________',
      '- Persona que reporta: ___________',
      '',
      'DESCRIPCIÓN DEL INCIDENTE:',
      '- Descripción objetiva de los hechos:',
      '  _________________________________',
      '- Circunstancias previas relevantes:',
      '  _________________________________',
      '- Consecuencias observadas:',
      '  _________________________________',
      '',
      'ACCIONES INMEDIATAS TOMADAS:',
      '- Medidas de protección aplicadas:',
      '  _________________________________',
      '- Comunicaciones realizadas:',
      '  _________________________________',
      '- Atención médica proporcionada:',
      '  _________________________________',
      '',
      '2. REGISTRO DE COMUNICACIONES',
      '',
      'COMUNICACIÓN CON AUTORIDADES:',
      '- Fecha: _____ Hora: _____ ',
      '- Organismo contactado: ___________',
      '- Persona de contacto: ___________',
      '- Información transmitida: ___________',
      '- Respuesta recibida: ___________',
      '- Próximos pasos acordados: ___________',
      '',
      'COMUNICACIÓN CON FAMILIAS:',
      '- Fecha: _____ Hora: _____',
      '- Familiar contactado: ___________',
      '- Método de comunicación: ___________',
      '- Información compartida: ___________',
      '- Reacción de la familia: ___________',
      '- Acuerdos alcanzados: ___________',
      '',
      '3. HOJA DE SEGUIMIENTO DE CASOS',
      '',
      'IDENTIFICACIÓN DEL CASO:',
      '- Número de caso: ___________',
      '- Menor afectado: ___________',
      '- Fecha de apertura: ___________',
      '- Delegado responsable: ___________',
      '- Nivel de gravedad: ___________',
      '',
      'CRONOLOGÍA DE ACTUACIONES:',
      '- Fecha | Acción realizada | Responsable | Resultado',
      '  _____|_________________|____________|___________',
      '  _____|_________________|____________|___________',
      '  _____|_________________|____________|___________',
      '',
      'ESTADO ACTUAL:',
      '- Situación del menor: ___________',
      '- Medidas de protección activas: ___________',
      '- Próximas acciones programadas: ___________',
      '- Fecha prevista de revisión: ___________',
      '',
      '4. PLANTILLA DE INFORME MENSUAL',
      '',
      'RESUMEN EJECUTIVO:',
      '- Total de casos atendidos: ___________',
      '- Casos nuevos del mes: ___________',
      '- Casos cerrados: ___________',
      '- Casos en seguimiento: ___________',
      '',
      'ANÁLISIS DE INCIDENCIAS:',
      '- Tipos de incidentes más frecuentes:',
      '  _________________________________',
      '- Factores de riesgo identificados:',
      '  _________________________________',
      '- Efectividad de medidas aplicadas:',
      '  _________________________________',
      '',
      'RECOMENDACIONES:',
      '- Áreas de mejora identificadas:',
      '  _________________________________',
      '- Propuestas de formación adicional:',
      '  _________________________________',
      '- Recursos necesarios:',
      '  _________________________________',
      '',
      '5. CHECK-LIST DE SUPERVISIÓN',
      '',
      'SUPERVISIÓN DE INSTALACIONES:',
      '□ Espacios seguros y bien iluminados',
      '□ Accesos controlados',
      '□ Zonas privadas identificadas',
      '□ Equipamiento en buen estado',
      '□ Señalización de emergencia visible',
      '',
      'SUPERVISIÓN DE ACTIVIDADES:',
      '□ Supervisión adulta adecuada',
      '□ Grupos de edad apropiados',
      '□ Actividades según protocolos',
      '□ Interacciones apropiadas',
      '□ Ambiente positivo y seguro',
      '',
      'SUPERVISIÓN DE PERSONAL:',
      '□ Cumplimiento del código de conducta',
      '□ Formación actualizada',
      '□ Documentación completa',
      '□ Comunicación efectiva',
      '□ Detección proactiva de riesgos'
    ]
  },

  {
    id: 'material-familias',
    titulo: 'Material para Familias',
    descripcion: 'Información y recursos para padres y tutores sobre protección LOPIVI',
    categoria: 'Comunicación',
    tamaño: '0.8 MB - 18 páginas',
    esencial: false,
    contenido: [
      'INFORMACIÓN LOPIVI PARA FAMILIAS',
      '',
      '1. ¿QUÉ ES LA LOPIVI Y CÓMO PROTEGE A TU HIJO/A?',
      '',
      'La Ley Orgánica de Protección Integral a la Infancia y la Adolescencia frente a la Violencia es una normativa que:',
      '',
      '✓ GARANTIZA un entorno seguro para todos los menores',
      '✓ ESTABLECE protocolos claros de protección',
      '✓ FORMA al personal en detección de riesgos',
      '✓ CREA sistemas de denuncia accesibles',
      '✓ PROMUEVE la participación de las familias',
      '',
      'BENEFICIOS PARA TU HIJO/A:',
      '- Actividades deportivas más seguras',
      '- Personal formado específicamente',
      '- Protocolos claros ante cualquier situación',
      '- Canales de comunicación abiertos',
      '- Respuesta rápida ante incidencias',
      '',
      '2. NUESTRO COMPROMISO CON LA PROTECCIÓN',
      '',
      'NUESTRA ENTIDAD SE COMPROMETE A:',
      '',
      '🛡️ PREVENIR situaciones de riesgo',
      '- Selección rigurosa del personal',
      '- Formación continua en protección',
      '- Supervisión constante de actividades',
      '- Instalaciones seguras y controladas',
      '',
      '👁️ DETECTAR señales de alarma',
      '- Observación profesional constante',
      '- Comunicación fluida con menores',
      '- Atención a cambios comportamentales',
      '- Coordinación con familias',
      '',
      '⚡ ACTUAR con rapidez y eficacia',
      '- Protocolos de emergencia claros',
      '- Comunicación inmediata con autoridades',
      '- Medidas de protección inmediatas',
      '- Seguimiento profesional continuo',
      '',
      '3. CÓMO PUEDES COLABORAR COMO FAMILIA',
      '',
      'COMUNICACIÓN ABIERTA:',
      '- Pregunta regularmente sobre las actividades',
      '- Escucha activamente las experiencias',
      '- Mantén diálogo sobre límites apropiados',
      '- Fomenta la confianza para contar problemas',
      '',
      'OBSERVACIÓN ATENTA:',
      '- Presta atención a cambios de comportamiento',
      '- Observa señales físicas o emocionales',
      '- Nota cambios en el interés por las actividades',
      '- Detecta miedos o rechazos inexplicables',
      '',
      'PARTICIPACIÓN ACTIVA:',
      '- Conoce al personal de la entidad',
      '- Participa en reuniones informativas',
      '- Colabora en actividades cuando sea posible',
      '- Comparte sugerencias de mejora',
      '',
      '4. CANALES DE COMUNICACIÓN DISPONIBLES',
      '',
      'PARA CONSULTAS GENERALES:',
      '📧 Email: info@[entidad].com',
      '📞 Teléfono: 900 XXX XXX',
      '🏢 Oficina: Horario de L-V 9:00-17:00',
      '',
      'PARA SITUACIONES URGENTES:',
      '🚨 Delegado de Protección: 600 XXX XXX',
      '📧 Email urgente: proteccion@[entidad].com',
      '🆘 Emergencias: 112',
      '',
      'PARA DENUNCIAS O CONSULTAS CONFIDENCIALES:',
      '📮 Buzón físico en recepción',
      '💻 Formulario web anónimo',
      '📞 Teléfono confidencial: 900 XXX XXX',
      '',
      '5. PREGUNTAS FRECUENTES DE LAS FAMILIAS',
      '',
      'P: ¿Mi hijo/a está seguro/a en las actividades?',
      'R: Sí. Tenemos protocolos estrictos de supervisión, personal formado y instalaciones seguras. Además, realizamos evaluaciones continuas.',
      '',
      'P: ¿Qué hago si mi hijo/a me cuenta algo preocupante?',
      'R: Escúchale con calma, no juzgues, documenta lo que te cuenta y contacta inmediatamente con nuestro delegado de protección.',
      '',
      'P: ¿Puedo conocer al personal que trabaja con mi hijo/a?',
      'R: Por supuesto. Organizamos reuniones informativas y estás invitado/a a conocer a todo el equipo.',
      '',
      'P: ¿Cómo puedo estar seguro/a de que se cumplen los protocolos?',
      'R: Realizamos auditorías internas regulares, formación continua del personal y evaluaciones externas periódicas.',
      '',
      '6. RECURSOS ADICIONALES PARA FAMILIAS',
      '',
      'INFORMACIÓN SOBRE PROTECCIÓN INFANTIL:',
      '- Ministerio de Derechos Sociales: www.mdsocialesa2030.gob.es',
      '- Fundación ANAR: www.anar.org',
      '- Save the Children: www.savethechildren.es',
      '',
      'LÍNEAS DE AYUDA ESPECIALIZADAS:',
      '- Teléfono ANAR: 900 20 20 10',
      '- Teléfono del Menor: 116 111',
      '- Chat ANAR: www.anar.org/chat-anar',
      '',
      'FORMACIÓN PARA FAMILIAS:',
      '- Talleres de comunicación familiar',
      '- Charlas sobre protección online',
      '- Sesiones de prevención de riesgos'
    ]
  },

  {
    id: 'documentacion-legal',
    titulo: 'Documentación Legal',
    descripcion: 'Normativa, legislación y contactos oficiales relevantes',
    categoria: 'Marco Legal',
    tamaño: '2.1 MB - 48 páginas',
    esencial: true,
    contenido: [
      'DOCUMENTACIÓN LEGAL LOPIVI',
      '',
      '1. MARCO NORMATIVO PRINCIPAL',
      '',
      'LEY ORGÁNICA 8/2021, de 4 de junio, de protección integral a la infancia y la adolescencia frente a la violencia (LOPIVI)',
      '',
      'ARTÍCULOS CLAVE PARA ENTIDADES DEPORTIVAS:',
      '',
      'Artículo 35. Deber de comunicación',
      'Cualquier persona que tenga conocimiento de un hecho que pudiera constituir violencia ejercida sobre una persona menor de edad está obligada a comunicarlo de forma inmediata a la autoridad competente.',
      '',
      'Artículo 47. Delegado o delegada de protección',
      'Las entidades que desarrollen actividades dirigidas a menores de edad deberán tener un delegado o delegada de protección que deberá conocer los protocolos en materia de prevención y protección.',
      '',
      'Artículo 48. Planes de protección',
      'Las entidades deberán elaborar y mantener actualizado un plan de protección que incluirá medidas de prevención, detección precoz, protección y asistencia.',
      '',
      'Artículo 49. Formación especializada',
      'El personal que trabaje habitualmente con menores deberá acreditar formación en derechos de la infancia y prevención, detección precoz y protección.',
      '',
      '2. NORMATIVA AUTONÓMICA APLICABLE',
      '',
      '[ESTA SECCIÓN SE PERSONALIZA SEGÚN LA COMUNIDAD AUTÓNOMA]',
      '',
      'EJEMPLO - COMUNIDAD DE MADRID:',
      '- Ley 6/1995, de 28 de marzo, de Garantías de los Derechos de la Infancia y la Adolescencia',
      '- Decreto 42/2022 de desarrollo de la LOPIVI en la Comunidad de Madrid',
      '',
      'EJEMPLO - ANDALUCÍA:',
      '- Ley 1/1998, de 20 de abril, de los Derechos y la Atención al Menor',
      '- Decreto 3/2004, por el que se establece el sistema de información sobre maltrato infantil',
      '',
      'EJEMPLO - CATALUÑA:',
      '- Ley 14/2010, de 27 de mayo, de los derechos y las oportunidades en la infancia y la adolescencia',
      '- Ley 15/2022, de 12 de julio, integral de reconocimiento del derecho a la identidad y expresión de género',
      '',
      '3. DIRECTORIO DE CONTACTOS OFICIALES',
      '',
      'SERVICIOS SOCIALES ESPECIALIZADOS:',
      '',
      'NACIONAL:',
      '- Ministerio de Derechos Sociales y Agenda 2030',
      '  Teléfono: 91 347 88 00',
      '  Email: contacto@mdsocialesa2030.gob.es',
      '',
      '- Observatorio de la Infancia',
      '  Teléfono: 91 347 88 37',
      '  Email: observatoriodelainfancia@mdsocialesa2030.gob.es',
      '',
      'SERVICIOS DE EMERGENCIA:',
      '- Emergencias generales: 112',
      '- Guardia Civil: 062',
      '- Policía Nacional: 091',
      '- Bomberos: 080',
      '',
      'LÍNEAS DE AYUDA ESPECIALIZADAS:',
      '- Teléfono ANAR: 900 20 20 10',
      '- Teléfono del Menor: 116 111',
      '- Teléfono contra el maltrato infantil: 116 006',
      '',
      'FISCALÍA DE MENORES:',
      '[CONTACTOS POR COMUNIDAD AUTÓNOMA]',
      '',
      'Madrid: Fiscalía Provincial de Madrid',
      'Teléfono: 91 493 25 00',
      'Dirección: C/ Bárbara de Braganza, 2, 28004 Madrid',
      '',
      'Barcelona: Fiscalía Provincial de Barcelona',
      'Teléfono: 93 344 21 00',
      'Dirección: Pg. Lluís Companys, 14-16, 08003 Barcelona',
      '',
      '4. FORMULARIOS OFICIALES',
      '',
      'FORMULARIO DE DENUNCIA ANTE FISCALÍA:',
      '',
      'DATOS DEL DENUNCIANTE:',
      'Nombre completo: ________________________',
      'DNI: ___________________________________',
      'Cargo en la entidad: ____________________',
      'Teléfono de contacto: ____________________',
      'Email: __________________________________',
      '',
      'DATOS DEL MENOR AFECTADO:',
      'Nombre completo: ________________________',
      'Fecha de nacimiento: ____________________',
      'Domicilio: ______________________________',
      'Datos de los representantes legales: ______',
      '________________________________________',
      '',
      'DESCRIPCIÓN DE LOS HECHOS:',
      'Fecha de los hechos: ____________________',
      'Lugar: _________________________________',
      'Descripción detallada: ___________________',
      '________________________________________',
      '________________________________________',
      '',
      'MEDIDAS ADOPTADAS:',
      'Medidas de protección inmediatas: _________',
      '________________________________________',
      'Comunicaciones realizadas: _______________',
      '________________________________________',
      '',
      '5. PROTOCOLO DE COORDINACIÓN INSTITUCIONAL',
      '',
      'ORDEN DE COMUNICACIÓN SEGÚN GRAVEDAD:',
      '',
      'SITUACIÓN DE RIESGO LEVE:',
      '1. Servicios sociales municipales',
      '2. Dirección de la entidad',
      '3. Familia (si procede)',
      '',
      'SITUACIÓN DE RIESGO MODERADO:',
      '1. Servicios sociales especializados',
      '2. Servicios sociales municipales',
      '3. Dirección de la entidad',
      '4. Familia (tras valoración)',
      '',
      'SITUACIÓN DE RIESGO GRAVE O EMERGENCIA:',
      '1. 112 (si hay riesgo vital)',
      '2. Fiscalía de menores',
      '3. Fuerzas de seguridad',
      '4. Servicios sociales especializados',
      '5. Dirección de la entidad',
      '',
      '6. ASPECTOS LEGALES IMPORTANTES',
      '',
      'OBLIGACIONES LEGALES:',
      '- Deber de comunicación inmediata',
      '- Confidencialidad de datos del menor',
      '- Colaboración con las autoridades',
      '- Mantenimiento de medidas de protección',
      '',
      'RESPONSABILIDADES PENALES:',
      '- Omisión del deber de socorro',
      '- No comunicación de delitos',
      '- Quebrantamiento de medidas',
      '- Revelación de secretos',
      '',
      'PROTECCIÓN DE DATOS:',
      '- RGPD aplicable a menores',
      '- Consentimiento de representantes legales',
      '- Tratamiento de datos sensibles',
      '- Cesión a autoridades competentes'
    ]
  },

  {
    id: 'herramientas-trabajo',
    titulo: 'Herramientas de Trabajo',
    descripcion: 'Check-lists, calendarios y herramientas prácticas para el día a día',
    categoria: 'Herramientas Prácticas',
    tamaño: '0.7 MB - 16 páginas',
    esencial: false,
    contenido: [
      'HERRAMIENTAS DE TRABAJO DEL DELEGADO',
      '',
      '1. CHECK-LIST DE INSPECCIÓN MENSUAL',
      '',
      'INSTALACIONES Y ESPACIOS:',
      '□ Vestuarios seguros y bien iluminados',
      '□ Accesos controlados y señalizados',
      '□ Espacios privados identificados correctamente',
      '□ Equipamiento deportivo en buen estado',
      '□ Sistemas de comunicación funcionando',
      '□ Señalización de emergencia visible',
      '□ Botiquines equipados y accesibles',
      '□ Zonas de descanso apropiadas',
      '',
      'SUPERVISIÓN DE ACTIVIDADES:',
      '□ Ratio adulto/menor apropiado',
      '□ Supervisión directa en todas las actividades',
      '□ Separación por grupos de edad cuando procede',
      '□ Actividades acorde a los protocolos',
      '□ Interacciones adulto-menor apropiadas',
      '□ Ambiente positivo y respetuoso',
      '□ Comunicación efectiva del personal',
      '□ Resolución adecuada de conflictos',
      '',
      'DOCUMENTACIÓN Y REGISTROS:',
      '□ Fichas de personal actualizadas',
      '□ Registros de incidentes al día',
      '□ Comunicaciones documentadas',
      '□ Protocolos accesibles al personal',
      '□ Contactos de emergencia actualizados',
      '□ Formación del personal registrada',
      '',
      '2. CALENDARIO DE ACTIVIDADES ANUALES',
      '',
      'ENERO:',
      '- Revisión anual del Plan de Protección',
      '- Actualización de contactos de emergencia',
      '- Planificación de formación anual',
      '',
      'FEBRERO:',
      '- Formación trimestral del personal',
      '- Evaluación de instalaciones post-navidad',
      '- Revisión de protocolos de actuación',
      '',
      'MARZO:',
      '- Auditoría interna del sistema',
      '- Reunión con familias sobre protección',
      '- Actualización de documentación legal',
      '',
      'ABRIL:',
      '- Formación específica en detección',
      '- Evaluación de casos del trimestre',
      '- Preparación temporada deportiva',
      '',
      'MAYO:',
      '- Formación trimestral del personal',
      '- Revisión de instalaciones pre-verano',
      '- Coordinación con servicios sociales',
      '',
      'JUNIO:',
      '- Planificación actividades de verano',
      '- Formación específica personal temporal',
      '- Evaluación semestral del plan',
      '',
      'JULIO-AGOSTO:',
      '- Supervisión intensiva (temporada alta)',
      '- Coordinación con campamentos',
      '- Seguimiento especial de casos',
      '',
      'SEPTIEMBRE:',
      '- Vuelta a la rutina: revisión protocolos',
      '- Formación de acogida personal nuevo',
      '- Evaluación post-verano',
      '',
      'OCTUBRE:',
      '- Formación trimestral del personal',
      '- Auditoría externa si procede',
      '- Preparación memorias anuales',
      '',
      'NOVIEMBRE:',
      '- Evaluación anual del personal',
      '- Planificación siguiente ejercicio',
      '- Coordinación con centros educativos',
      '',
      'DICIEMBRE:',
      '- Cierre evaluación anual',
      '- Memoria anual de protección',
      '- Planificación navidad y año nuevo',
      '',
      '3. EVALUACIÓN DE RIESGOS POR ACTIVIDAD',
      '',
      'ACTIVIDADES DEPORTIVAS GRUPALES:',
      'Riesgo: BAJO-MEDIO',
      'Medidas: Supervisión constante, grupos equilibrados',
      'Supervisión: 1 adulto cada 8-10 menores',
      'Espacios: Abiertos y visibles',
      '',
      'ACTIVIDADES EN VESTUARIOS:',
      'Riesgo: ALTO',
      'Medidas: Supervisión intensiva, acceso controlado',
      'Supervisión: 2 adultos mínimo, puerta abierta',
      'Espacios: Separación por edad y género',
      '',
      'DESPLAZAMIENTOS Y VIAJES:',
      'Riesgo: MEDIO',
      'Medidas: Autorización familiar, supervisión continua',
      'Supervisión: 1 adulto cada 6 menores',
      'Espacios: Transporte autorizado, alojamientos seguros',
      '',
      'ACTIVIDADES INDIVIDUALES:',
      'Riesgo: ALTO',
      'Medidas: Evitar uno-a-uno, espacios abiertos',
      'Supervisión: Siempre con testigos',
      'Espacios: Visibles desde exterior',
      '',
      '4. HERRAMIENTAS DE COMUNICACIÓN',
      '',
      'PLANTILLA DE EMAIL URGENTE:',
      '',
      'Asunto: [URGENTE LOPIVI] - [Breve descripción]',
      '',
      'Estimado/a [destinatario],',
      '',
      'Me dirijo a usted con carácter URGENTE en mi función de Delegado de Protección de [Entidad] para comunicar:',
      '',
      'SITUACIÓN: [Descripción objetiva]',
      'MENOR AFECTADO: [Iniciales, edad]',
      'FECHA/HORA: [Cuándo ocurrió]',
      'MEDIDAS ADOPTADAS: [Acciones inmediatas]',
      '',
      'SOLICITO: [Qué necesita]',
      'CONTACTO INMEDIATO: [Teléfono disponible]',
      '',
      'Quedo a la espera de su respuesta urgente.',
      '',
      'Atentamente,',
      '[Nombre del Delegado]',
      '[Datos de contacto]',
      '',
      'PLANTILLA DE COMUNICACIÓN CON FAMILIAS:',
      '',
      'Estimada familia de [nombre del menor],',
      '',
      'Me pongo en contacto con ustedes en mi función de Delegado de Protección para informarles sobre [situación].',
      '',
      'HECHOS: [Descripción apropiada para la familia]',
      'MEDIDAS: [Qué se ha hecho para proteger al menor]',
      'PRÓXIMOS PASOS: [Qué va a ocurrir]',
      '',
      'Entiendo que esta información puede resultar preocupante. Estoy disponible para resolver cualquier duda en [contacto].',
      '',
      'Nuestro compromiso es garantizar la seguridad y bienestar de [nombre del menor].',
      '',
      'Atentamente,',
      '[Nombre del Delegado]',
      '',
      '5. INDICADORES DE SEGUIMIENTO',
      '',
      'INDICADORES CUANTITATIVOS:',
      '- Número de casos detectados/mes',
      '- Tiempo de respuesta promedio',
      '- Porcentaje de personal formado',
      '- Número de comunicaciones con autoridades',
      '- Casos resueltos satisfactoriamente',
      '',
      'INDICADORES CUALITATIVOS:',
      '- Satisfacción de las familias',
      '- Ambiente de seguridad percibido',
      '- Efectividad de las medidas',
      '- Coordinación con otros servicios',
      '- Mejora continua del sistema',
      '',
      'OBJETIVOS ANUALES RECOMENDADOS:',
      '- 100% del personal formado anualmente',
      '- Tiempo de respuesta < 24 horas',
      '- 0 casos graves sin detectar',
      '- Satisfacción familiar > 90%',
      '- Coordinación efectiva con servicios'
    ]
  }
]

// Funciones de utilidad
export function obtenerDocumentoPorId(id: string): DocumentoLOPIVI | undefined {
  return DOCUMENTOS_LOPIVI.find(doc => doc.id === id)
}

export function obtenerDocumentosEsenciales(): DocumentoLOPIVI[] {
  return DOCUMENTOS_LOPIVI.filter(doc => doc.esencial)
}

export function obtenerDocumentosPorCategoria(categoria: string): DocumentoLOPIVI[] {
  return DOCUMENTOS_LOPIVI.filter(doc => doc.categoria === categoria)
}

export function generarContenidoPDF(documento: DocumentoLOPIVI): string {
  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${documento.titulo} - Custodia360</title>
  <style>
    body {
      font-family: 'Times New Roman', serif;
      margin: 40px;
      line-height: 1.6;
      color: #333;
    }
    .header {
      text-align: center;
      border-bottom: 3px solid #ff6600;
      padding-bottom: 20px;
      margin-bottom: 40px;
    }
    .logo {
      font-size: 24px;
      font-weight: bold;
      color: #ff6600;
      margin-bottom: 10px;
    }
    .titulo {
      font-size: 28px;
      color: #2c3e50;
      margin: 20px 0;
      font-weight: bold;
    }
    .subtitulo {
      font-size: 16px;
      color: #7f8c8d;
      margin-bottom: 20px;
    }
    .contenido {
      text-align: left;
      font-size: 14px;
      line-height: 1.8;
    }
    .seccion {
      margin: 30px 0;
    }
    .subseccion {
      margin: 20px 0;
      padding-left: 20px;
    }
    .lista {
      margin: 10px 0;
      padding-left: 30px;
    }
    .footer {
      margin-top: 60px;
      border-top: 1px solid #ddd;
      padding-top: 20px;
      text-align: center;
      font-size: 12px;
      color: #666;
    }
    .importante {
      background: #fffbf0;
      border-left: 4px solid #ff6600;
      padding: 15px;
      margin: 20px 0;
    }
    .checklist {
      background: #f8f9fa;
      padding: 15px;
      border-radius: 5px;
      margin: 15px 0;
    }
  </style>
</head>
<body>
  <div class="header">
    <div class="logo">CUSTODIA360</div>
    <h1 class="titulo">${documento.titulo}</h1>
    <p class="subtitulo">${documento.descripcion}</p>
    <p class="subtitulo">Categoría: ${documento.categoria} | ${documento.tamaño}</p>
  </div>

  <div class="contenido">
    ${documento.contenido.map(linea => {
      if (linea === '') return '<br>';
      if (linea.startsWith('□')) return `<div class="checklist">${linea}</div>`;
      if (linea.includes('IMPORTANTE') || linea.includes('URGENTE')) return `<div class="importante">${linea}</div>`;
      if (linea.match(/^\d+\./)) return `<div class="seccion"><strong>${linea}</strong></div>`;
      if (linea.startsWith('-')) return `<div class="lista">${linea}</div>`;
      return `<p>${linea}</p>`;
    }).join('')}
  </div>

  <div class="footer">
    <p>Documento generado por Custodia360</p>
    <p>Cumplimiento LOPIVI - Protección Integral de Menores</p>
    <p>© ${new Date().getFullYear()} Custodia360. Todos los derechos reservados.</p>
  </div>
</body>
</html>
  `
}
