# Alternative Netlify configuration for static export
# Use this if the main configuration fails
# Rename this file to netlify.toml to use it

[build]
  command = "npm ci --legacy-peer-deps && npm run build:static"
  publish = "out"

[build.environment]
  NODE_VERSION = "20"
  NODE_OPTIONS = "--max-old-space-size=8192"

  # Static export specific settings
  NEXT_OUTPUT = "export"
  SKIP_TYPE_CHECK = "true"
  DISABLE_ESLINT = "true"
  NPM_FLAGS = "--legacy-peer-deps"

  # Environment variables (same as main config)
  NEXT_PUBLIC_SUPABASE_URL = "https://gkoyqfusawhnobvkoijc.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdrb3lxZnVzYXdobm9idmtvaWpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyODMzOTQsImV4cCI6MjA3MTg1OTM5NH0.8PhAfdlfpiLih4_QqrfWRbn-gZ8eeWX7NaTGpO-9hyY"
  SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdrb3lxZnVzYXdobm9idmtvaWpjIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NjI4MzM5NCwiZXhwIjoyMDcxODU5Mzk0fQ.9oKkdWJsUEQaVXhOE4Uf4Nx6a0-8BZ5hNjdl_EyIJQM"
  RESEND_API_KEY = "re_JfPp939X_84TnwFXTiDRqMtUfdd2omgRA"
  RESEND_FROM_EMAIL = "noreply@custodia360.es"
  DEMO_MODE = "false"
  NEXT_PUBLIC_APP_URL = "https://custodia360.netlify.app"
  CRON_SECRET_TOKEN = "custodia360-cron-secret-2025"
  PDFSHIFT_API_KEY = "sk_3f24779f1fb6b4fa0a2bf6bfe6d25019fa8a19c6"
  BOE_MONITOREO_ACTIVO = "true"
  BOE_FRECUENCIA_DIAS = "15"
  AUDIT_RETENTION_YEARS = "5"
  AUDIT_TIMEZONE = "Europe/Madrid"
  LOPIVI_COMPLIANCE_MODE = "true"

# Headers for static files
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cache-Control = "public, max-age=31536000, immutable"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
